name: ${project.parent.name}
version: ${project.version}
main: ${project.groupId}.bungeecord.${project.parent.name}Plugin
author: Chickenpowerrr
description: ${project.description}
softdepend: [LuckPerms]